### ISSUE TITLE
Renew WALLY Security Cert

### ISSUE THREAD

**Issue by jakemorr** [bcgov/WALLY#759]
**Describe the task**
Wally's cert is due to expire October 30th, we need to renew it and have a new cert in place before then. 

**Purpose**
maintain the security of the application and not degrade the image of the app with its users.

**Acceptance Criteria**
- [ ] Wally has a new Cert

**Additional context**
- Former Susteam Dev has done this work previously
- Documentation: https://apps.nrs.gov.bc.ca/int/confluence/display/SUSTEAM/Entrust+Cert+Creation
- update this ticket as you progress: https://apps.nrs.gov.bc.ca/int/jira/browse/INFRA-24511?
- Wally SO can provide financial coding when it is required

**Comment by jakemorr** [comment]
ticket needs an estimate when work is started

**Comment by PaulGarewal** [comment]
### Task Progress Update

- **Contact with David Claveau**: I have reached out to David Claveau, and he has provided me with an updated document outlining the procedure for updating product certificates. I will use this to update the [Confluence page](https://apps.nrs.gov.bc.ca/int/confluence/display/SUSTEAM/Entrust+Cert+Creation).
  
- **Cert Renewal Request**: I have submitted the certificate renewal request to NRIDS infrastructure. The response time is typically about a week, and I will wait for their reply before proceeding further.

- **Private Key and CSR Generation**: I have successfully generated the private key and CSR for WALLY. These will be updated on OpenShift once we receive the response from NRIDS.

**Comment by PaulGarewal** [comment]
### Task Progress Update

- **WALLY Certificate Renewal Files Received**: We have received the renewed certificate files from the NRIDS Service Centre for the WALLY environment. 

- **Next Steps**: We will proceed with the review and implementation of these files on OpenShift. This process will ensure that WALLY functions as expected with the new certificate. 

- **Testing**: Once the update is complete, a functionality check will be performed to verify that WALLY is fully operational with the renewed certificates.

Further updates will be provided as we proceed with the verification steps.
